# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r_packages: covr

env:
  - SHINYSEL_REQUIRE_SELENIUM=true

services: docker

before_script:
  - ./scripts/selenium-start
  - R CMD INSTALL .

after_success:
  - cat shinysel.Rcheck/tests/testthat.Rout
  - Rscript -e 'covr::codecov()'
