# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r_packages: covr

services: docker

before_script:
  - ./scripts/selenium-start

after_success:
  - cat shinysel.Rcheck/tests/testthat.Rout
  - Rscript -e 'covr::codecov()'
